// File: app.js
// Author: Mehul Jodhani
// Date: 30 Jan 2025

// Importing required modules
import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

// Getting __dirname in ES module format
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Creating the express app
const app = express();

// Middlewares to handle JSON and form data
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Serving static files from dist folder (generated by Webpack)
app.use(express.static(path.resolve(__dirname, '../../dist')));

// This route handles all GET requests that are not handled before
// It sends index.html from dist folder so Navigo can take over routing
app.get('*', (req, res) => {
  res.sendFile(path.resolve(__dirname, '../../dist/index.html'));
});

// Error handler - catches server errors
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).send('Something broke!');
});

// Exporting the app to be used in the main server file
export default app;
